### ISSUE TITLE
Auto detect location

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1426]
See: http://market.open-classifieds.com/oc-panel/support/ticket/19660

**Comment by neo22s** [comment]
Thanks Oliver. I know about the Choose Location in the footer. But just how I mentioned before, what if I don't want to choose a location? I obviously X out of the pop up modal, but then with every homepage load, the choose your location modal keeps popping in. 

The only point I am trying to make is that I think it would be more user friendly for the customer, if it that was a little clearer. Also, I think it would be good, if the cookies that save the location would have an expiration, 

let's say every 30 minutes, so that if you are mobile and you are moving, it does realize that your location changes and it doesn't pop up the same locations from the previous location when I am in a different state. 
Also Oliver, don't you think it would be a little nicer if the customer can get redirected to the actual homepage and it doesn't refresh the listings page? If the homepage was localized with the ads based on the location you chose,
I think that would improve the quality enormously for customers with many ads.

Thanks again for this effort you put in in improving this software.

**Comment by neo22s** [comment]
Review if we can improve this.

**Comment by Chinese1904** [comment]
It's awesome to see you got my enhancement worked on. Now, this would still not allow the visitor to go back to the homepage and they would always get forwarded to the listings page, which another concern was. Is this behavior your intention?

**Comment by oliverds** [comment]
Not sure about localised homepage. Create a new route config to handle localised homepage? /home/location?

What do you think? @neo22s

**Comment by neo22s** [comment]
What if we filter the results from the homepage with the location of the cookie? that will fix it all...no redirect nothing else...
