### ISSUE TITLE
third level category nesting

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1567]
I was just wondering whether this is something you have been wondering about adding. Check out classilist.org to see it in action. Click on the category "Language" or "Business" and it will start opening up the other hidden categories. I would definitely make this a premium theme feature if you think about adding it

**Comment by neo22s** [comment]
And what happens if theres 1000's of categories? .... that could easily happen. 

10 top categories * 10 sub categories * 10 categories each subcategory and then your site starts rendering extremely slow.

KEY is to have the less categories as possible. New sites like Wallapop only have 5 categories! thats all they need.

Also this is related to a theme, each theme works differently. 

Thanks for the suggestion but no for this ;)

**Comment by Chinese1904** [comment]
True! But again, this is much better than wallapop ;)
Again, you're right, the way I was doing it though, I had an $order array, and I was just working it down, instead of doing the foreach loop. Still, you're right, there is more database queries this way, and it won't be efficient for customers with many categories.

**Comment by neo22s** [comment]
;) thanks again!
