### ISSUE TITLE
Update bootstrap to 3.3.6

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1600]
http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/

OE, OC, Yclas I know...it sucks xD

**Comment by oliverds** [comment]
Can’t do a pull-requests yet because [CDN Bootswatch](https://www.bootstrapcdn.com/bootswatch/) haven’t been updated to 3.3.6.

**Comment by neo22s** [comment]
now they have ;)

**Comment by oliverds** [comment]
I mean I have several [commits](https://github.com/oliverds/openclassifieds2/commits/master) on queue to do a pull-request but since I have updated already Bootswatch CDN version on a [commit](https://github.com/oliverds/openclassifieds2/commit/da2e5c50cc4a7ae9c44d53340408ce5bcbcd5070) it breaks OC styles if CDN option is enabled.

Same for OE and Yclas.

Hopefully they will update Bootswatch version very soon otherwise I will have to revert some commits :(

**Comment by neo22s** [comment]
we can use http://www.jsdelivr.com/projects/bootswatch they area already updated ;)

**Comment by oliverds** [comment]
You are right! Changing `maxcdn.bootstrapcdn.com` to `cdn.jsdelivr.net`.

**Comment by oliverds** [comment]
Now http://www.jsdelivr.com/projects/bootstrap is outdated (3.3.5). Hahaha.

Would have been better to change "Bootstrap" to jsdelivr.net too so users do not have to resolve two domains.

**Comment by neo22s** [comment]
Went back??? :O damn yeah its better for sure same domain

**Comment by oliverds** [comment]
Actually this issue should be kept open. Move **Bootstrap** CDN assets to jsDelivr is still pending until they update to 3.3.6.
