### ISSUE TITLE
https security issues

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1676]
I was setting up HTTPS on my site and I noticed that the SSL icon would only appear for a second and then disappear. There is a security issue with `favico-0.3.8.min.js`: 

![error](http://i.imgur.com/LsOPEw8.png)

I updated to `favico-0.3.10.min.js`. Anyhow, similar issues appear. This is the error log I get with Chrome. Above is the error log with Safari. 

![error](http://i.imgur.com/uRUg6Jr.png)

Can any of you replicate these issues?

**Comment by neo22s** [comment]
this can be closed I think, correct?

**Comment by oliverds** [comment]
@Chinese1904 

MIME type errors are solved with https://github.com/open-classifieds/common/commit/0ea844a4591612026b4fb9ac7044c7a94b3c55a0

"Cross-Origin" it's because favicon.ico is requested via HTTP. I think you have to re-upload your favicon at https://classilist.org/oc-panel/theme/options to update the favicon path config to https://classilist.org/images/favicon.ico.

**Comment by Chinese1904** [comment]
@oliverds 
thanks for the advise! I just fixed it and it works perfectly.
