### ISSUE TITLE
Optional fields - oc-panel/fields/index

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1720]
When pressing Save for optional fields on Settings -> Custom Fields,  I am getting this error:

![optional-fields](https://cloud.githubusercontent.com/assets/11571490/12583629/6668639e-c44c-11e5-9bf5-194f4c57dd92.png)

**Comment by neo22s** [comment]
thats really strange, on 2.7.0, correct?

**Comment by kotsios5** [comment]
Yes, on 2.7.0.

**Comment by neo22s** [comment]
mmmm ok @oliverds will take a look, on yclas is not happening, no?

**Comment by kotsios5** [comment]
Same on yclas

**Comment by neo22s** [comment]
currently live??? where can I test and fix this?

**Comment by neo22s** [comment]
Yep I can see it in classifiedsbarcelona.com

**Comment by kotsios5** [comment]
I can reproduce it here: http://constantinos.yclas.com/oc-panel/fields/index

**Comment by oliverds** [comment]
Ok thats because we are validating the form submission at https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/panel/settings.php#L44

Perhaps we should remove "Optional Fields" section on http://reoc.lo/oc-panel/fields/index since those options are already at http://reoc.lo/oc-panel/settings/form under "Advertisement Fields" section?

**Comment by neo22s** [comment]
cool by me ;)
