### ISSUE TITLE
Small bugs found

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1832]
1.*Preview of media image is not working (it was closed at last issue). *
I still cannot see this. The URL is wrong, look: 
http://reoc.lo/images/cms/C:\xampp\htdocs\openclassifieds2\images\cms\1460104048.people-fish-market-marketplace
Could be my local environment also.

2. *Under tools the tabbed tools are awesome but they all have an active class on my environment. * 
![a67a5284-0197-11e6-89d4-0879c3c50a72](https://cloud.githubusercontent.com/assets/11768128/14521345/0927d800-0253-11e6-84e0-0d60d70f695b.png)

3.** Active menu item must remain when menu is folded**
![fbe12e14-0197-11e6-86c2-400049077e04](https://cloud.githubusercontent.com/assets/11768128/14521347/0e3a39c8-0253-11e6-9349-27d259aa91d2.png)

**Comment by oliverds** [comment]
1. It seems fine to me. Must be something with running PHP on Windows :(

2. Fixed with https://github.com/oliverds/common/commit/b07e4e44620ccce592e71df91be107feb5ae9df2

3. I have spend some time on it. Problem is that if we keep "active" class then mentisMenu always open the second level navigation and it's annoying. That's why I remove the class at line https://github.com/oliverds/openclassifieds2/blob/master/themes/default/js/oc-panel/sidebar.js#L37
<img width="270" alt="screen shot 2016-04-14 at 11 24 30 am" src="https://cloud.githubusercontent.com/assets/7003648/14535441/80670212-0233-11e6-9507-81c83218d4ba.png">
