### ISSUE TITLE
Paguelo Fácil payment gateway

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#2022]
Integración pasarela de pago

http://www.paguelofacil.com/guia-de-integracion-en-pagina-web/

https://trello.com/c/HVHvGGps/1314-paguelofacil

**Comment by oliverds** [comment]
I followed the integration guide but haven't properly tested because Pagofacil don't have a developers account, requires a live website and ask to register callback uri by email.

**Comment by neo22s** [comment]
hahah....many of them I had same issue. What I did is uplaod in a site like dontcode.com and test there...

**Comment by oliverds** [comment]
Also I can't open a _normal_ account because there are [a lot of requirements](http://www.paguelofacil.com/afiliacion_empreserial/) and is [NOT free](http://www.paguelofacil.com/afiliacion_empreserial/), and only one callback uri can be registered per user.

I will test it when compraventazonalivre customer configures its account.

**Comment by neo22s** [comment]
ok, lets do that!
